= Manage Drafts Syntaxes
== Why use different syntaxes?

:name-of-an-attribute: value of the attribute
:attr reference: https://docs.asciidoctor.org/asciidoc/latest/attributes/attribute-entries/

== Asciidoc Quick Reference

=== *Sidebars:*
[sidebar]
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.

=== Blocks

.Onomatopoeia
====
The book hit the floor with a *thud*.

He could hear doves *cooing* in the pine trees`' branches.
====

.Optional title
[example]
This is an example of an example block.

.Optional Title
****
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.

TIP: They can contain any type of content.

.Source code block in a sidebar
[source,js]
----
const { expect, expectCalledWith, heredoc } = require('../test/test-utils')
----
****
== Links

*Example 10. Autolinks, URL macro, and mailto macro*
https://asciidoctor.org - automatic!

https://asciidoctor.org[Asciidoctor]

devel@discuss.example.org

mailto:devel@discuss.example.org[Discuss]

mailto:join@discuss.example.org[Subscribe,Subscribe me, I want to join!]

asciidoctor.org - automatic!

Asciidoctor

devel@discuss.example.org

Discuss

Subscribe

*Example 11. URL macros with attributes*
https://discuss.asciidoctor.org[Discuss Asciidoctor,role=external,window=_blank]

https://discuss.asciidoctor.org[Discuss Asciidoctor^]

Discuss Asciidoctor

Discuss Asciidoctor

The link: macro prefix is not required when the target starts with a URL scheme like https:. The URL scheme acts as an implicit macro prefix.
If the link text contains a comma and the text is followed by one or more named attributes, you must enclose the text in double quotes. Otherwise, the text will be cut off at the comma (and the remaining text will get pulled into the attribute parsing).
*Example 12. URLs with spaces and special characters*
link:++https://example.org/?q=[a b]++[URL with special characters]

https://example.org/?q=%5Ba%20b%5D[URL with special characters]
Example 13. Link to relative file
link:index.html[Docs]
Example 14. Link using a Windows UNC path
link:\\server\share\whitepaper.pdf[Whitepaper]
Example 15. Inline anchors
[[bookmark-a]]Inline anchors make arbitrary content referenceable.

[#bookmark-b]#Inline anchors can be applied to a phrase like this one.#

anchor:bookmark-c[]Use a cross reference to link to this location.

[[bookmark-d,last paragraph]]The xreflabel attribute will be used as link text in the cross-reference link.
Example 16. Cross references
See <<paragraphs>> to learn how to write paragraphs.

Learn how to organize the document into <<section-titles,sections>>.
View result of Example 16
See Paragraphs to learn how to write paragraphs.

Learn how to organize the document into sections.


*Example 17. Inter-document cross references*
Refer to xref:document-b.adoc#section-b[Section B of Document B] for more information.

If you never return from xref:document-b.adoc[Document B], we'll
